"""Generate a new Genius-{purpose} domain repository scaffold."""
from __future__ import annotations

from pathlib import Path

from genius.naming import genius_name, assert_valid_repo_name

DIRS = [
    "schemas",
    "mastery",
    "capabilities",
    "claims",
    "sources",
    "sources/NOTES",
    "challenges",
    "challenges/foundation",
    "challenges/reproduction",
    "challenges/implementation",
    "challenges/adversarial",
    "challenges/operational",
    "challenges/transfer",
    "challenges/frontier",
    "evidence",
    "evidence/receipts",
    "evidence/counterevidence",
    "evidence/manifests",
    "implementations/reference",
    "implementations/production",
    "implementations/competing-designs",
    "experiments",
    "benchmarks/baselines",
    "benchmarks/results",
    "verification/properties",
    "verification/fuzz",
    "verification/static-analysis",
    "verification/dynamic-analysis",
    "verification/models",
    "verification/proofs",
    "operations/observability",
    "operations/failure-injection",
    "operations/recovery",
    "operations/migration",
    "operations/runbooks",
    "synthesis",
    "teaching/reconstruction",
    "teaching/explainers",
    "teaching/assessments",
    "original-work",
    "frontier",
    "interfaces",
    "tools",
    "tests",
    ".github/workflows",
]


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def create_domain(purpose: str, dest_parent: Path, *, force: bool = False) -> Path:
    name = genius_name(purpose)
    assert_valid_repo_name(name)
    root = dest_parent / name
    if root.exists() and any(root.iterdir()) and not force:
        raise FileExistsError(f"refusing to overwrite non-empty directory: {root}")
    root.mkdir(parents=True, exist_ok=True)

    for d in DIRS:
        (root / d).mkdir(parents=True, exist_ok=True)

    purpose_title = name.removeprefix("Genius-")

    _write(
        root / "GENIUS.yaml",
        f"""schema_version: 2
repository: {name}
purpose: {purpose_title}
family: Genius
doctrine: mastery-not-skills
mastery_loop:
  - map
  - research
  - model
  - build
  - break
  - measure
  - verify
  - operate
  - explain
  - synthesize
  - prove
  - expand
  - teach
evidence_required: true
growth_model: open-ended-cumulative
mastery_representation: claim-evidence-graph+vector
composition_contract: interfaces/COMPOSITION.yaml
capability_anatomy_contract: capabilities/STACK.yaml
teaching_contract: teaching/TEACHING.yaml
""",
    )

    _write(
        root / "README.md",
        f"""# {name}

Domain mastery repository for **{purpose_title}**.

Identity is hyphenated only: `{name}`.

Scaffold generated by Genius-Mastery kernel. Scaffold != mastery.
Evidence receipts required before elevating claim status beyond `mapped`.

The vertical capability anatomy begins at `capabilities/STACK.yaml` and is governed by the universal contract in Genius-Mastery.
""",
    )

    _write(
        root / "capabilities/STACK.yaml",
        f"""schema_version: 1
id: {name.lower()}.vertical-excellence
name: {purpose_title} Vertical Excellence
purpose: Make {purpose_title} a kernel-up, executable, verifiable, continuously improving Genius domain entity.
state: mapped
objective:
  current_reality: Seed domain scaffold exists.
  desired_reality: Every material {purpose_title} outcome can be decomposed into real dependencies, executable capabilities, verification, and retained gain.
  success_conditions:
    - Required capability layers are explicit for the current mission.
    - Missing primitives are distinguished from failed implementations.
    - Alternate routes are considered before a scoped blocked state.
    - Real effects are independently verified before being claimed.
layers:
  reality: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  physical_substrate: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  compute: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  firmware_kernel_os: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  runtime: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  code: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  training_data: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  training_method: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  model: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  model_serving: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  identity_persona: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  agent_kernel: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  instructions: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  context: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  representation: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  memory: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  knowledge: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  perception: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  multimodal: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  language: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  reasoning: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  metacognition: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  planning: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  skills: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  capability_composition: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  tools: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  apis: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  connectors_mcp: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  browser_computer_use: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  files_documents: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  artifact_generation: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  communication: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  state_persistence: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  time_events_automation: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  swarm_multi_agent: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  orchestration: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  verification: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  observability: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  reliability_recovery: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  security_integrity: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  resource_economics: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  human_interaction: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  teaching: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  domain_expertise: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  real_world_effect: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
  learning_evolution: {{inspection_prompts: [], required: [], available: [], missing: [], alternate_routes: [], failure_modes: [], improvement_targets: []}}
dependencies: []
action:
  preconditions: []
  steps: []
  expected_effects: []
  postconditions: []
  alternate_routes: []
  failure_modes: []
  recovery_routes: []
verification:
  acceptance:
    - Claims of capability are bounded by observed evidence.
  tests: []
  evidence_refs: []
  independent_readback: []
mission_impact:
  mission_relevance: 1.0
  necessity: 1.0
  criticality: 1.0
  sensitivity: 1.0
  substitutability: 0.0
  downstream_centrality: 1.0
  improvement_leverage: 1.0
  rationale: Vertical capability anatomy is the domain's reusable decomposition and improvement substrate.
evolution:
  current_bottleneck: Populate mission-specific layers with observed evidence.
  improvement_targets: []
  affected_capabilities: []
  newly_possible_compositions: []
  next_frontier: []
""",
    )

    _write(
        root / "claims/CLAIMS.yaml",
        "schema_version: 1\nclaims: []\n",
    )
    _write(
        root / "sources/REGISTRY.yaml",
        "schema_version: 1\nsources: []\n",
    )
    _write(
        root / "challenges/REGISTRY.yaml",
        "schema_version: 1\nchallenges: []\n",
    )
    _write(
        root / "interfaces/COMPOSITION.yaml",
        f"""spec_version: 1
repository: {name}
provides: []
consumes:
  - repository: Genius-Mastery
    capability: mastery.kernel.schemas
    minimum_spec_version: 1
    reason: Shared contracts and identity rules.
  - repository: Genius-Mastery
    capability: mastery.kernel.capability-anatomy
    minimum_spec_version: 1
    reason: Shared kernel-up decomposition model for domain capabilities.
  - repository: Genius-Mastery
    capability: mastery.kernel.capability-schema
    minimum_spec_version: 1
    reason: Shared machine-readable universal capability contract.
""",
    )
    _write(
        root / "mastery/VECTOR.yaml",
        f"""schema_version: 1
repository: {name}
dimensions: {{}}
notes: "Seed vector; recompute from claims/evidence."
""",
    )
    _write(
        root / "mastery/RETENTION.yaml",
        """schema_version: 1
strategy: spaced-revalidation+transfer
policies:
  - revalidate volatile claims when upstream versions change
  - stale evidence preserved for lineage
  - passing once never creates permanent mastery status
reviews: []
""",
    )
    _write(
        root / "teaching/TEACHING.yaml",
        f"""schema_version: 1
teacher: {name}
subject: {purpose_title} mastery
method:
  explain:
    - first principles
    - dependencies and failure modes
  demonstrate:
    - complete one evidence-backed example
  reconstruct:
    - rebuild from a blank state without copying the answer
  transfer:
    - apply the method to a materially different case
learner:
  starting_state: novice-or-unknown
  target_state: independently-reconstructs-and-transfers-verified-methods
  allowed_support: []
verification:
  acceptance:
    - Learner can explain the method in its own words.
    - Learner can reconstruct the result from a blank state.
    - Learner can transfer the method to a novel case.
    - Learner can identify important failure modes and alternate routes.
  evidence_refs: []
  transfer_challenges: []
  counterevidence: []
outcome_metrics:
  reconstruction_success: 0.0
  transfer_success: 0.0
  explanation_quality: 0.0
  independence: 0.0
""",
    )

    _write(
        root / "mastery/MAP.md",
        f"# Mastery Map: {name}\n\n(Populate first principles, mechanisms, and open questions.)\n",
    )
    _write(
        root / "mastery/ROADMAP.yaml",
        "schema_version: 1\nnear_term: []\nmid_term: []\nfrontier: []\n",
    )
    _write(
        root / "frontier/QUEUE.yaml",
        "schema_version: 1\nitems: []\n",
    )
    _write(root / "evidence/ledger.jsonl", "")
    _write(
        root / "CHANGELOG.md",
        f"# Changelog: {name}\n\n## [0.1.0-seed]\n\n- Generated by genius new\n",
    )
    _write(
        root / "LICENSE",
        "MIT License\n\nCopyright (c) 2026\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software...\n",
    )
    _write(
        root / ".gitignore",
        "__pycache__/\n.venv/\n.env\n.DS_Store\n.pytest_cache/\n*.log\nevidence/receipts/local/\n",
    )
    _write(
        root / "tools/validate.py",
        '''#!/usr/bin/env python3
"""Standalone structural validator for a generated Genius repository."""
from pathlib import Path
import re
import sys
import yaml

REPO_RE = re.compile(r"^Genius-[A-Za-z0-9._-]+$")


def load_yaml(path):
    with path.open(encoding="utf-8") as f:
        return yaml.safe_load(f)


def main():
    root = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
    errors = []

    genius_path = root / "GENIUS.yaml"
    if not genius_path.exists():
        errors.append("GENIUS.yaml missing")
    else:
        genius = load_yaml(genius_path) or {}
        if genius.get("schema_version") != 2:
            errors.append("GENIUS.yaml schema_version must be 2")
        repo = genius.get("repository")
        if not isinstance(repo, str) or not REPO_RE.match(repo):
            errors.append("GENIUS.yaml repository identity invalid")
        if genius.get("family") != "Genius":
            errors.append("GENIUS.yaml family must be Genius")
        if genius.get("doctrine") != "mastery-not-skills":
            errors.append("GENIUS.yaml doctrine must be mastery-not-skills")

        for field in ("composition_contract", "capability_anatomy_contract", "capability_graph", "teaching_contract"):
            target = genius.get(field)
            if target and not (root / target).exists():
                errors.append(f"{field} target missing: {target}")

        role_target = genius.get("role_brief")
        if role_target:
            role_path = root / role_target
            if not role_path.exists():
                errors.append(f"role_brief target missing: {role_target}")
            else:
                role = load_yaml(role_path) or {}
                if role.get("schema_version") != 1:
                    errors.append("ROLE.yaml schema_version must be 1")
                if not role.get("role"):
                    errors.append("ROLE.yaml role missing")
                outcomes = role.get("outcomes")
                if not isinstance(outcomes, list) or not outcomes:
                    errors.append("ROLE.yaml outcomes must be non-empty")

    stack_path = root / "capabilities" / "STACK.yaml"
    if not stack_path.exists():
        errors.append("capabilities/STACK.yaml missing")
    else:
        stack = load_yaml(stack_path) or {}
        if stack.get("schema_version") != 1:
            errors.append("capabilities/STACK.yaml schema_version must be 1")
        if not stack.get("id") or not stack.get("purpose"):
            errors.append("capabilities/STACK.yaml identity incomplete")
        objective = stack.get("objective") or {}
        if not objective.get("desired_reality"):
            errors.append("capabilities/STACK.yaml desired_reality missing")
        if not isinstance(stack.get("layers"), dict) or not stack["layers"]:
            errors.append("capabilities/STACK.yaml layers missing")
        verification = stack.get("verification") or {}
        if not verification.get("acceptance"):
            errors.append("capabilities/STACK.yaml verification.acceptance missing")
        if not isinstance(stack.get("mission_impact"), dict):
            errors.append("capabilities/STACK.yaml mission_impact missing")

    graph_target = genius.get("capability_graph")
    if graph_target:
        graph_path = root / graph_target
        if not graph_path.exists():
            errors.append(f"capability_graph target missing: {graph_target}")
        else:
            graph = load_yaml(graph_path) or {}
            nodes = graph.get("nodes")
            edges = graph.get("edges")
            if graph.get("schema_version") != 1:
                errors.append("capability graph schema_version must be 1")
            if not isinstance(nodes, list) or not isinstance(edges, list):
                errors.append("capability graph nodes/edges must be lists")
            else:
                ids = {
                    node.get("id")
                    for node in nodes
                    if isinstance(node, dict) and node.get("id")
                }
                if len(ids) != len(nodes):
                    errors.append("capability graph node ids must be present and unique")
                for edge in edges:
                    if (
                        not isinstance(edge, dict)
                        or edge.get("from") not in ids
                        or edge.get("to") not in ids
                        or not edge.get("relation")
                    ):
                        errors.append("capability graph contains invalid edge")

    teaching_path = root / "teaching" / "TEACHING.yaml"
    if not teaching_path.exists():
        errors.append("teaching/TEACHING.yaml missing")
    else:
        teaching = load_yaml(teaching_path) or {}
        if teaching.get("schema_version") != 1:
            errors.append("teaching/TEACHING.yaml schema_version must be 1")
        if not teaching.get("teacher") or not teaching.get("subject"):
            errors.append("teaching/TEACHING.yaml identity incomplete")
        method = teaching.get("method") or {}
        for phase in ("explain", "demonstrate", "reconstruct", "transfer"):
            if not method.get(phase):
                errors.append(f"teaching/TEACHING.yaml method.{phase} missing")
        verification = teaching.get("verification") or {}
        if not verification.get("acceptance"):
            errors.append("teaching/TEACHING.yaml verification.acceptance missing")

    comp_path = root / "interfaces" / "COMPOSITION.yaml"
    if not comp_path.exists():
        errors.append("interfaces/COMPOSITION.yaml missing")

    if errors:
        print("FAIL")
        for error in errors:
            print("  -", error)
        return 1
    print("PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
''',
    )
    _write(
        root / ".github/workflows/validate.yml",
        """name: validate-contract
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install pyyaml
      - run: python tools/validate.py .
""",
    )
    return root
