"""Generate a new Genius-{purpose} domain repository scaffold."""
from __future__ import annotations

from pathlib import Path

from genius.naming import genius_name, assert_valid_repo_name

DIRS = [
    "schemas",
    "mastery",
    "claims",
    "sources",
    "sources/NOTES",
    "challenges",
    "challenges/foundation",
    "challenges/reproduction",
    "challenges/implementation",
    "challenges/adversarial",
    "challenges/operational",
    "challenges/transfer",
    "challenges/frontier",
    "evidence",
    "evidence/receipts",
    "evidence/counterevidence",
    "evidence/manifests",
    "implementations/reference",
    "implementations/production",
    "implementations/competing-designs",
    "experiments",
    "benchmarks/baselines",
    "benchmarks/results",
    "verification/properties",
    "verification/fuzz",
    "verification/static-analysis",
    "verification/dynamic-analysis",
    "verification/models",
    "verification/proofs",
    "operations/observability",
    "operations/failure-injection",
    "operations/recovery",
    "operations/migration",
    "operations/runbooks",
    "synthesis",
    "teaching/reconstruction",
    "teaching/explainers",
    "teaching/assessments",
    "original-work",
    "frontier",
    "interfaces",
    "tools",
    "tests",
    ".github/workflows",
]


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def create_domain(purpose: str, dest_parent: Path, *, force: bool = False) -> Path:
    name = genius_name(purpose)
    assert_valid_repo_name(name)
    root = dest_parent / name
    if root.exists() and any(root.iterdir()) and not force:
        raise FileExistsError(f"refusing to overwrite non-empty directory: {root}")
    root.mkdir(parents=True, exist_ok=True)

    for d in DIRS:
        (root / d).mkdir(parents=True, exist_ok=True)

    purpose_title = name.removeprefix("Genius-")

    _write(
        root / "GENIUS.yaml",
        f"""schema_version: 2
repository: {name}
purpose: {purpose_title}
family: Genius
doctrine: mastery-not-skills
mastery_loop:
  - map
  - research
  - model
  - build
  - break
  - measure
  - verify
  - operate
  - explain
  - synthesize
  - prove
  - expand
evidence_required: true
growth_model: open-ended-cumulative
mastery_representation: claim-evidence-graph+vector
composition_contract: interfaces/COMPOSITION.yaml
""",
    )

    _write(
        root / "README.md",
        f"""# {name}

Domain mastery repository for **{purpose_title}**.

Identity is hyphenated only: `{name}`.

Scaffold generated by Genius-Mastery kernel. Scaffold ≠ mastery.
Evidence receipts required before elevating claim status beyond `mapped`.
""",
    )

    _write(
        root / "claims/CLAIMS.yaml",
        "schema_version: 1\nclaims: []\n",
    )
    _write(
        root / "sources/REGISTRY.yaml",
        "schema_version: 1\nsources: []\n",
    )
    _write(
        root / "challenges/REGISTRY.yaml",
        "schema_version: 1\nchallenges: []\n",
    )
    _write(
        root / "interfaces/COMPOSITION.yaml",
        f"""spec_version: 1
repository: {name}
provides: []
consumes:
  - repository: Genius-Mastery
    capability: mastery.kernel.schemas
    minimum_spec_version: 1
    reason: Shared contracts and identity rules.
""",
    )
    _write(
        root / "mastery/VECTOR.yaml",
        f"""schema_version: 1
repository: {name}
dimensions: {{}}
notes: "Seed vector — recompute from claims/evidence."
""",
    )
    _write(
        root / "mastery/RETENTION.yaml",
        """schema_version: 1
strategy: spaced-revalidation+transfer
policies:
  - revalidate volatile claims when upstream versions change
  - stale evidence preserved for lineage
  - passing once never creates permanent mastery status
reviews: []
""",
    )
    _write(
        root / "mastery/MAP.md",
        f"# Mastery Map — {name}\n\n(Populate first principles, mechanisms, and open questions.)\n",
    )
    _write(
        root / "mastery/ROADMAP.yaml",
        "schema_version: 1\nnear_term: []\nmid_term: []\nfrontier: []\n",
    )
    _write(
        root / "frontier/QUEUE.yaml",
        "schema_version: 1\nitems: []\n",
    )
    _write(root / "evidence/ledger.jsonl", "")
    _write(
        root / "CHANGELOG.md",
        f"# Changelog — {name}\n\n## [0.1.0-seed]\n\n- Generated by genius new\n",
    )
    _write(
        root / "LICENSE",
        "MIT License\n\nCopyright (c) 2026\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software...\n",
    )
    _write(
        root / ".gitignore",
        "__pycache__/\n.venv/\n.env\n.DS_Store\n.pytest_cache/\n*.log\nevidence/receipts/local/\n",
    )
    _write(
        root / "tools/validate.py",
        '''#!/usr/bin/env python3
"""Thin local validator — prefer `genius validate` when the kernel is installed."""
from pathlib import Path
import sys
try:
    from genius.validate import validate_repo
except ImportError:
    print("Install genius-mastery (pip install -e path/to/Genius-Mastery) for full validation.")
    sys.exit(2)
errs = validate_repo(Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve())
if errs:
    print("FAIL")
    for e in errs:
        print("  -", e)
    sys.exit(1)
print("PASS")
''',
    )
    _write(
        root / ".github/workflows/validate.yml",
        """name: validate-contract
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install pyyaml
      - run: python tools/validate.py .
""",
    )
    return root
